using System.Collections.Generic;

namespace OrclWAMP
{
    /// <summary>Bulgarian translations, keyed by the English text used in the code.</summary>
    internal static class LangBg
    {
        public static readonly Dictionary<string, string> Texts = new Dictionary<string, string>
        {
            // --- AppConfigs.cs
            { "{0}: {1} is larger than 50 MB – skipped", "{0}: {1} е по-голям от 50 MB – пропуснат" },
            { "skipped – the package password was not entered", "пропуснато – паролата на пакета не е въведена" },
            { "skipped (not an allowed location)", "пропуснато (непозволено местоположение)" },
            { "VS Code is not installed yet – extensions were not installed", "VS Code още не е инсталиран – разширенията не са инсталирани" },
            { "{0} of {1} VS Code extensions installed", "Инсталирани са {0} от {1} разширения на VS Code" },
            { "Firefox bookmarks from {0}", "Отметки на Firefox от {0}" },
            { "Firefox bookmark backup placed on the Desktop: {0}", "Архивът с отметки на Firefox е поставен на работния плот: {0}" },
            // --- AppConfigsForm.cs
            { "App settings & bookmarks to take along", "Настройки на приложения и отметки за пренасяне" },
            { "App", "Приложение" },
            { "What's included", "Какво включва" },
            { "Note", "Бележка" },
            { "Needs a password-protected package", "Изисква пакет, защитен с парола" },
            { "SSH keys are only taken along in a password-protected package. Tick \"Protect with password\" in the main window first.", "SSH ключовете се пренасят само в пакет, защитен с парола. Първо отметнете „Защита с парола“ в главния прозорец." },
            { "Cancel", "Отказ" },
            { "Use these apps", "Използвай тези приложения" },
            { "None of the supported apps were found on this PC.", "На този компютър не е открито нито едно от поддържаните приложения." },
            { "Settings of these apps (and your browser bookmarks) are copied into the package. On the new PC they are put in place after the apps are installed – with a backup first.", "Настройките на тези приложения (и отметките от браузъра) се копират в пакета. На новия компютър те се поставят след инсталирането на приложенията – като първо се прави резервно копие." },
            { "App settings & bookmarks", "Настройки на приложения и отметки" },
            { "Apply app settings & bookmarks", "Прилагане на настройки на приложения и отметки" },
            { "Items", "Елементи" },
            { "Asks for the package password", "Изисква паролата на пакета" },
            { "Apply ticked", "Приложи отметнатите" },
            { "Undo last apply", "Отмяна на последното прилагане" },
            { "Close", "Затвори" },
            { "App settings and bookmarks from \"{0}\". Install the apps first, then apply. Files that get replaced are backed up – \"Undo last apply\" puts them back.", "Настройки на приложения и отметки от „{0}“. Първо инсталирайте приложенията, след това приложете. Заменените файлове се архивират – „Отмяна на последното прилагане“ ги връща обратно." },
            { "Nothing is ticked.", "Нищо не е отметнато." },
            { "Please close these apps first, otherwise they may overwrite the settings when they exit:\r\n\r\n{0}\r\n\r\nContinue anyway?", "Първо затворете тези приложения, иначе може да презапишат настройките при излизане:\r\n\r\n{0}\r\n\r\nПродължаване въпреки това?" },
            { "Applying {0} app(s)", "Прилагане на настройките на {0} приложения" },
            { "{0} applied, {1} skipped.", "Приложени: {0}, пропуснати: {1}." },
            { "Put back the app settings as they were before the last \"Apply\"?", "Да се върнат ли настройките на приложенията както бяха преди последното „Прилагане“?" },
            { "{0} restored.", "Възстановени: {0}." },
            // --- Downloads.cs
            { "Direct download", "Директно изтегляне" },
            { "Your link", "Ваша връзка" },
            { "Official download page", "Официална страница за изтегляне" },
            { "Web app address", "Адрес на уеб приложението" },
            { "No link", "Няма връзка" },
            { "The download was incomplete.", "Изтеглянето е непълно." },
            { "The server stopped responding.", "Сървърът спря да отговаря." },
            // --- FilesForm.cs
            { "Personal files to take along", "Лични файлове за пренасяне" },
            { "Folder", "Папка" },
            { "Location", "Местоположение" },
            { "Size", "Размер" },
            { "Files", "Файлове" },
            { "Use these folders", "Използвай тези папки" },
            { "Remove folder", "Премахни папката" },
            { "Add folder…", "Добави папка…" },
            { "These folders are copied into the migration package (make sure the USB drive is big enough) and put back on the new PC. Folders kept in OneDrive are not ticked – they come back by themselves when you sign in to OneDrive.", "Тези папки се копират в пакета за миграция (уверете се, че USB устройството е достатъчно голямо) и се връщат на новия компютър. Папките в OneDrive не са отметнати – те се връщат сами, когато влезете в OneDrive." },
            { "Personal files", "Лични файлове" },
            { "Copy personal files to this PC", "Копиране на лични файлове на този компютър" },
            { "Copy to", "Копиране в" },
            { "Status", "Състояние" },
            { "Was:", "Беше:" },
            { "Copy ticked folders", "Копирай отметнатите папки" },
            { "Stop", "Спри" },
            { "Change destination…", "Промени местоназначението…" },
            { "If a file already exists:", "Ако файлът вече съществува:" },
            { "Keep both (rename the copy)", "Запази и двата (преименувай копието)" },
            { "Skip it", "Пропусни го" },
            { "Replace it", "Замени го" },
            { "Personal files from \"{0}\" ({1} in total). Identical files are skipped automatically. Double-click a folder to change where it goes.", "Лични файлове от „{0}“ (общо {1}). Еднаквите файлове се пропускат автоматично. Щракнете два пъти върху папка, за да промените къде да отиде." },
            { "Files are still being copied. Stop and close?", "Файловете все още се копират. Спиране и затваряне?" },
            { "measuring…", "измерване…" },
            { "Kept in OneDrive – comes back by itself", "В OneDrive – връща се сама" },
            { "Measuring folders…", "Измерване на папките…" },
            { "{0} folder(s), {1} selected", "Папки: {0}, избрани: {1}" },
            { "Choose a folder to take along", "Изберете папка за пренасяне" },
            { "Please choose a folder, not a whole drive.", "Изберете папка, а не цяло устройство." },
            { "Where should \"{0}\" go?", "Къде да отиде „{0}“?" },
            { "No folders are ticked.", "Няма отметнати папки." },
            { "Drive {0} may not have enough free space for these files. Copy anyway?", "Устройство {0} може да няма достатъчно свободно място за тези файлове. Копиране въпреки това?" },
            { "Copying…", "Копиране…" },
            { "{0} -> {1}", "{0} -> {1}" },
            { "from {0}", "от {0}" },
            { "{0} copied, {1} skipped, {2} failed", "Копирани: {0}, пропуснати: {1}, неуспешни: {2}" },
            { "Stopped.", "Спряно." },
            { "{0} files copied ({1}), {2} skipped, {3} renamed, {4} failed.", "Копирани файлове: {0} ({1}), пропуснати: {2}, преименувани: {3}, неуспешни: {4}." },
            { "{0} of {1} – {2}", "{0} от {1} – {2}" },
            // --- MainForm.cs
            { "Show system items", "Показване на системни елементи" },
            { "Install the exact same versions", "Инсталиране на точно същите версии" },
            { "Run as administrator on the new PC (fewer UAC prompts)", "Изпълнение като администратор на новия компютър (по-малко UAC запитвания)" },
            { "Restart the new PC when finished", "Рестартиране на новия компютър след приключване" },
            { "Windows settings", "Настройки на Windows" },
            { "Protect with password", "Защита с парола" },
            { "Apps winget can install", "Приложения, които winget може да инсталира" },
            { "Apps to install manually", "Приложения за ръчно инсталиране" },
            { "All apps", "Всички приложения" },
            { "Name", "Име" },
            { "Package ID", "ID на пакета" },
            { "Version", "Версия" },
            { "Source", "Източник" },
            { "Migration package:", "Пакет за миграция:" },
            { "Timeout per app (min):", "Лимит за приложение (мин):" },
            { "Off (recommended): install the newest version.\r\nOn: install the same version as on this PC (falls back to newest if that version is gone).", "Изключено (препоръчително): инсталира се най-новата версия.\r\nВключено: инсталира се същата версия като на този компютър (или най-новата, ако тази версия вече я няма)." },
            { "OrclWAMP asks for administrator rights once at the start on the new PC,\r\nso the individual installers don't each show a UAC prompt.\r\n\r\nOff (recommended for most people): apps install for the signed-in user;\r\nmachine-wide installers show their own UAC prompt. A few per-user apps refuse to install as administrator.", "OrclWAMP иска администраторски права веднъж в началото на новия компютър,\r\nза да не показва всеки инсталатор свое UAC запитване.\r\n\r\nИзключено (препоръчително за повечето хора): приложенията се инсталират за влезлия потребител;\r\nинсталаторите за целия компютър показват свое UAC запитване. Някои приложения за отделен потребител отказват да се инсталират като администратор." },
            { "Also list Windows components, drivers and runtimes that have no winget package.", "Показват се и компоненти на Windows, драйвери и среди за изпълнение, които нямат winget пакет." },
            { "Also take along:", "Пренасяне още на:" },
            { "Choose…", "Избор…" },
            { "Personal Windows settings: touchpad gestures, mouse, keyboard & languages,\r\ntaskbar & Explorer options, colours, wallpaper, regional formats, power, fonts.", "Лични настройки на Windows: жестове на тъчпада, мишка, клавиатура и езици,\r\nлента на задачите и Explorer, цветове, тапет, регионални формати, захранване, шрифтове." },
            { "Settings of apps like Windows Terminal, Notepad++, VS Code, Git, and your browser bookmarks.", "Настройки на приложения като Windows Terminal, Notepad++, VS Code, Git и отметките от браузъра." },
            { "Copies Desktop, Documents, Pictures… into the package (needs enough space on the USB drive).", "Копира работния плот, документите, снимките… в пакета (нужно е достатъчно място на USB устройството)." },
            { "Choose a password for the sensitive parts of the package (Wi-Fi passwords, SSH keys). You need it again on the new PC – OrclWAMP can't recover it.", "Изберете парола за чувствителните части на пакета (пароли за Wi-Fi, SSH ключове). Ще ви трябва отново на новия компютър – OrclWAMP не може да я възстанови." },
            { "Encrypts Wi-Fi passwords and SSH keys in the package with a password (AES-256).", "Шифрова паролите за Wi-Fi и SSH ключовете в пакета с парола (AES-256)." },
            { "Create migration package…", "Създаване на пакет за миграция…" },
            { "Search:", "Търсене:" },
            { "Show:", "Показване:" },
            { "All", "Всички" },
            { "None", "Нито едно" },
            { "Invert", "Обърни избора" },
            { "Scan this PC", "Сканиране на този компютър" },
            { "Add apps from winget…", "Добавяне на приложения от winget…" },
            { "Find winget packages for manual apps…", "Търсене на winget пакети за ръчните приложения…" },
            { "Manual apps && downloads…", "Ръчни приложения и изтегляния…" },
            { "Searches winget by name for the apps it couldn't link to a package\r\n(e.g. Store versions). You confirm every match.", "Търси в winget по име приложенията, които не е свързал с пакет\r\n(напр. версии от Store). Вие потвърждавате всяко съвпадение." },
            { "Download links for apps winget can't install – download them one by one or all at once.", "Връзки за изтегляне на приложения, които winget не може да инсталира – изтеглете ги едно по едно или всички наведнъж." },
            { "App updates…", "Актуализации на приложения…" },
            { "Shows apps on this PC that have a newer version and updates the ticked ones.", "Показва приложенията на този компютър, които имат по-нова версия, и актуализира отметнатите." },
            { "Winget App Migration Program", "Програма за миграция на приложения с winget" },
            { "Ready.", "Готово." },
            { "Please wait – the migration package is still being written.", "Изчакайте – пакетът за миграция все още се записва." },
            { "&File", "&Файл" },
            { "&Scan this PC", "&Сканиране на този компютър" },
            { "&Open app list / profile…", "&Отваряне на списък / профил…" },
            { "Save app list as &profile…", "Запис на списъка като &профил…" },
            { "&Export list to CSV…", "&Експорт на списъка в CSV…" },
            { "&Create migration package…", "Създаване на пакет за &миграция…" },
            { "E&xit", "Из&ход" },
            { "&Tools", "&Инструменти" },
            { "&Add apps from winget…", "&Добавяне на приложения от winget…" },
            { "&Find winget packages for manual apps…", "&Търсене на winget пакети за ръчните приложения…" },
            { "&Manual apps && downloads…", "&Ръчни приложения и изтегляния…" },
            { "&Install from a migration package (restore mode)…", "&Инсталиране от пакет за миграция (режим на възстановяване)…" },
            { "App &updates…", "&Актуализации на приложения…" },
            { "Check &winget", "Проверка на &winget" },
            { "&Help", "&Помощ" },
            { "&How it works", "&Как работи" },
            { "Command-line options", "Параметри на командния ред" },
            { "Project page on &GitHub", "Страница на проекта в &GitHub" },
            { "&About", "&За програмата" },
            { "Tick selected rows", "Отметни избраните редове" },
            { "Untick selected rows", "Премахни отметката от избраните редове" },
            { "Copy package ID", "Копирай ID на пакета" },
            { "Show package on winstall.app", "Покажи пакета в winstall.app" },
            { "Search the web for this app", "Търси това приложение в интернет" },
            { "Remove from list", "Премахни от списъка" },
            { "1. On the OLD PC: click \"Scan this PC\". OrclWAMP lists every installed app and checks which ones winget can install.", "1. На СТАРИЯ компютър: натиснете „Сканиране на този компютър“. OrclWAMP показва всяко инсталирано приложение и проверява кои от тях winget може да инсталира." },
            { "2. Untick anything you don't want. Apps marked \"to install manually\" have no winget package; they go into a report so you don't forget them.", "2. Махнете отметката от всичко, което не искате. Приложенията, отбелязани „за ръчно инсталиране“, нямат winget пакет; те влизат в отчет, за да не ги забравите." },
            { "3. Click \"Create migration package…\" and pick your USB stick. An \"OrclWAMP-Migration\" folder is written there.", "3. Натиснете „Създаване на пакет за миграция…“ и изберете USB флашката. Там се записва папка „OrclWAMP-Migration“." },
            { "4. On the NEW PC: connect to the internet, open the folder and double-click Install.cmd (or OrclWAMP.exe). Check the list and click \"Start installation\".", "4. На НОВИЯ компютър: свържете се с интернет, отворете папката и щракнете два пъти върху Install.cmd (или OrclWAMP.exe). Прегледайте списъка и натиснете „Начало на инсталирането“." },
            { "Tip: use \"Add apps from winget…\" to add apps this PC doesn't have, and File > Save profile to reuse a list.", "Съвет: с „Добавяне на приложения от winget…“ добавяте приложения, които ги няма на този компютър, а с Файл > Запис на списъка като профил можете да използвате списъка отново." },
            { "Looking for winget…", "Търсене на winget…" },
            { "winget was not found.", "winget не е открит." },
            { "winget (Windows Package Manager) was not found on this PC.", "winget (Windows Package Manager) не е открит на този компютър." },
            { "It comes with \"App Installer\" from the Microsoft Store. Open the download page now?", "Той идва с „App Installer“ от Microsoft Store. Да се отвори ли страницата за изтегляне сега?" },
            { "winget {0} found.", "Открит е winget {0}." },
            { "winget {0} is installed:", "Инсталиран е winget {0}:" },
            { "Scan complete: {0} apps can be installed with winget, {1} need a manual install.", "Сканирането завърши: {0} приложения могат да се инсталират с winget, {1} изискват ръчно инсталиране." },
            { "Tip: \"Find winget packages for manual apps\" often finds more.", "Съвет: „Търсене на winget пакети за ръчните приложения“ често открива още." },
            { "Scan cancelled.", "Сканирането е отменено." },
            { "Scan failed.", "Сканирането е неуспешно." },
            { "The scan failed:", "Сканирането е неуспешно:" },
            { "Ticked = install on the new PC", "Отметнато = инсталиране на новия компютър" },
            { "No winget package. Ticked = add to the manual-install report", "Няма winget пакет. Отметнато = добавяне в отчета за ръчно инсталиране" },
            { "From {0}", "От {0}" },
            { "{0} of {1} winget apps selected  ·  {2} on manual list  ·  {3} shown", "Избрани {0} от {1} winget приложения  ·  {2} в ръчния списък  ·  {3} показани" },
            { "winget is not available on this PC.", "winget не е наличен на този компютър." },
            { "Added {0} app(s).", "Добавени приложения: {0}." },
            { "Nothing is selected. Scan the PC (or open a profile) and tick the apps to migrate first.", "Нищо не е избрано. Първо сканирайте компютъра (или отворете профил) и отметнете приложенията за миграция." },
            { "Choose your USB flash drive (or any folder).\r\nAn \"{0}\" folder will be created there.", "Изберете USB флашката (или произволна папка).\r\nТам ще бъде създадена папка „{0}“." },
            { "A migration package already exists in\r\n{0}\r\n\r\nReplace it?", "Вече има пакет за миграция в\r\n{0}\r\n\r\nДа бъде ли заменен?" },
            { "The personal files need about {0}, but the drive only has {1} free.\r\n\r\nWrite the package anyway?", "Личните файлове заемат около {0}, а на устройството има само {1} свободно място.\r\n\r\nЗаписване на пакета въпреки това?" },
            { "This drive uses FAT32, which can't store files of 4 GB or larger – such files will be skipped and listed in the log.", "Това устройство използва FAT32, което не може да съхранява файлове от 4 GB или по-големи – такива файлове ще бъдат пропуснати и записани в дневника." },
            { "Copying personal files: {0} of {1} – {2}", "Копиране на лични файлове: {0} от {1} – {2}" },
            { "Writing migration package…", "Записване на пакета за миграция…" },
            { "Migration package written to", "Пакетът за миграция е записан в" },
            { "Migration package created:\r\n{0}", "Пакетът за миграция е създаден:\r\n{0}" },
            { "• {0} apps will be installed automatically", "• {0} приложения ще бъдат инсталирани автоматично" },
            { "• {0} apps are on the manual-install list", "• {0} приложения са в списъка за ръчно инсталиране" },
            { "• {0} groups of Windows settings", "• {0} групи настройки на Windows" },
            { "• settings of {0} app(s) / browsers", "• настройки на {0} приложения / браузъри" },
            { "• {0} personal folder(s), {1}", "• {0} лични папки, {1}" },
            { "• sensitive items protected with your password", "• чувствителните елементи са защитени с вашата парола" },
            { "On the new PC, open this folder and double-click Install.cmd.", "На новия компютър отворете тази папка и щракнете два пъти върху Install.cmd." },
            { "Open the folder now?", "Да се отвори ли папката сега?" },
            { "Cancelled – the package is incomplete.", "Отменено – пакетът е непълен." },
            { "Writing the package was cancelled. The folder is incomplete – create the package again before using it.", "Записването на пакета беше отменено. Папката е непълна – създайте пакета отново, преди да го използвате." },
            { "Could not write the package.", "Пакетът не можа да бъде записан." },
            { "Could not write the migration package:", "Пакетът за миграция не можа да бъде записан:" },
            { "Nothing is selected.", "Нищо не е избрано." },
            { "OrclWAMP app list (*.json)|*.json", "Списък с приложения на OrclWAMP (*.json)|*.json" },
            { "Saved {0}", "Записано: {0}" },
            { "App lists (*.json)|*.json|All files|*.*", "Списъци с приложения (*.json)|*.json|Всички файлове|*.*" },
            { "Open an OrclWAMP app list or a winget export file", "Отваряне на списък с приложения на OrclWAMP или файл, експортиран от winget" },
            { "Could not read the file:", "Файлът не можа да бъде прочетен:" },
            { "Replace the current list?\r\n\r\nYes = replace,  No = add to the current list", "Да се замени ли текущият списък?\r\n\r\nДа = замяна,  Не = добавяне към текущия списък" },
            { "Loaded {0} packages from {1}.", "Заредени пакети: {0} от {1}." },
            { "The list is empty – scan first.", "Списъкът е празен – първо сканирайте." },
            { "CSV file (*.csv)|*.csv", "CSV файл (*.csv)|*.csv" },
            { "Exported {0}", "Експортирано: {0}" },
            { "There are no manual-install apps in the list. Scan the PC first.", "В списъка няма приложения за ръчно инсталиране. Първо сканирайте компютъра." },
            { "Searching winget {0} of {1}: {2}", "Търсене в winget {0} от {1}: {2}" },
            { "Search cancelled.", "Търсенето е отменено." },
            { "No winget packages found for the manual apps.", "Не са открити winget пакети за ръчните приложения." },
            { "winget has no packages with the same names as the manual-install apps.", "В winget няма пакети със същите имена като приложенията за ръчно инсталиране." },
            { "No matches used.", "Не са използвани съвпадения." },
            { "{0} app(s) will now be installed with winget.", "{0} приложения вече ще се инсталират с winget." },
            { "Settings of {0} app(s) will be included.", "Ще бъдат включени настройките на {0} приложения." },
            { "{0} personal folder(s), {1}, will be included.", "Ще бъдат включени {0} лични папки, {1}." },
            { "{0} group(s) of Windows settings will be included.", "Ще бъдат включени {0} групи настройки на Windows." },
            { "OrclWAMP package (OrclWAMP-packages.json)|*.json|All files|*.*", "Пакет на OrclWAMP (OrclWAMP-packages.json)|*.json|Всички файлове|*.*" },
            { "Open a migration package", "Отваряне на пакет за миграция" },
            // --- ManualAppsForm.cs
            { "Manual apps & downloads", "Ръчни приложения и изтегляния" },
            { "Publisher", "Издател" },
            { "Download link", "Връзка за изтегляне" },
            { "Download ticked", "Изтегли отметнатите" },
            { "Download all", "Изтегли всички" },
            { "Open downloads folder", "Отвори папката с изтеглянията" },
            { "Printable checklist", "Списък за печат" },
            { "{0} apps can't be installed by winget.  {1} can be downloaded directly, {2} have an official download page, {3} have no link OrclWAMP can be sure of.", "{0} приложения не могат да се инсталират с winget.  {1} могат да се изтеглят директно, {2} имат официална страница за изтегляне, за {3} OrclWAMP няма сигурна връзка." },
            { "Double-click an app to download it (or open its page). Right-click to set your own link. Files are saved to: {0}", "Щракнете два пъти върху приложение, за да го изтеглите (или да отворите страницата му). С десен бутон задавате своя връзка. Файловете се записват в: {0}" },
            { "Download / open link", "Изтегли / отвори връзката" },
            { "Run downloaded installer", "Стартирай изтегления инсталатор" },
            { "Show file in folder", "Покажи файла в папката" },
            { "Set download link…", "Задай връзка за изтегляне…" },
            { "Copy link", "Копирай връзката" },
            { "Open publisher website", "Отвори сайта на издателя" },
            { "No publisher website is known for this app.", "За това приложение не е известен сайт на издателя." },
            { "No download link OrclWAMP can be sure of – right-click > Set download link…", "OrclWAMP няма сигурна връзка за изтегляне – десен бутон > Задай връзка за изтегляне…" },
            { "Install manually (right-click for options)", "Инсталирайте ръчно (десен бутон за опции)" },
            { "No apps are ticked.", "Няма отметнати приложения." },
            { "Downloading {0} of {1}: {2}", "Изтегляне {0} от {1}: {2}" },
            { "{0} app(s) can't be downloaded directly – they have an official download page instead.\r\n\r\nOpen these pages in your browser now?", "{0} приложения не могат да се изтеглят директно – вместо това имат официална страница за изтегляне.\r\n\r\nДа се отворят ли тези страници в браузъра сега?" },
            { "Opened web app – install it from the browser menu", "Уеб приложението е отворено – инсталирайте го от менюто на браузъра" },
            { "Opened download page", "Страницата за изтегляне е отворена" },
            { "{0} downloaded, {1} page(s) opened, {2} failed, {3} without a link.", "Изтеглени: {0}, отворени страници: {1}, неуспешни: {2}, без връзка: {3}." },
            { "{0} downloaded, {1} page(s) opened, {2} failed.", "Изтеглени: {0}, отворени страници: {1}, неуспешни: {2}." },
            { "{0} installer(s) saved to:\r\n{1}\r\n\r\nDouble-click an app in the list to run its installer.", "Записани инсталатори: {0}, в:\r\n{1}\r\n\r\nЩракнете два пъти върху приложение в списъка, за да стартирате инсталатора му." },
            { "{0} app(s) have no link OrclWAMP can be sure of. Right-click them to search the web or set your own link.", "За {0} приложения OrclWAMP няма сигурна връзка. Щракнете с десен бутон върху тях, за да потърсите в интернет или да зададете своя връзка." },
            { "Downloading…", "Изтегляне…" },
            { "Link is a web page – opened it in the browser", "Връзката е уеб страница – отворена е в браузъра" },
            { "Downloaded: {0}  (double-click to install)", "Изтеглено: {0}  (щракнете два пъти за инсталиране)" },
            { "Stopped", "Спряно" },
            { "Download failed: {0}", "Неуспешно изтегляне: {0}" },
            { "Run the installer for {0}?\r\n\r\n{1}", "Да се стартира ли инсталаторът на {0}?\r\n\r\n{1}" },
            { "Could not start the installer:", "Инсталаторът не можа да бъде стартиран:" },
            { "Download link for {0}", "Връзка за изтегляне на {0}" },
            { "Paste a download link (a direct installer link or the official download page).\r\nLeave empty to remove your link.", "Поставете връзка за изтегляне (директна връзка към инсталатор или официалната страница за изтегляне).\r\nОставете празно, за да премахнете своята връзка." },
            { "That isn't a web address (it must start with https:// or http://).", "Това не е уеб адрес (трябва да започва с https:// или http://)." },
            { "OK", "OK" },
            // --- MatchesForm.cs
            { "winget packages found for manual apps", "Открити winget пакети за ръчните приложения" },
            { "App on this PC", "Приложение на този компютър" },
            { "winget package", "winget пакет" },
            { "Only package with exactly this name", "Единственият пакет с точно това име" },
            { "Several packages have this name – tick the right one (or none)", "Няколко пакета имат това име – отметнете правилния (или нито един)" },
            { "Install these with winget", "Инсталирай тези с winget" },
            { "winget has packages with exactly the same name for {0} app(s). Ticked ones move to the automatic install list.", "winget има пакети с точно същото име за {0} приложения. Отметнатите се преместват в списъка за автоматично инсталиране." },
            { "Packages are matched by name only – check the publisher/ID before using them. Names with several matches start unticked.", "Пакетите са намерени само по име – проверете издателя/ID преди да ги използвате. Имената с няколко съвпадения започват без отметка." },
            // --- MigrationReport.cs
            { "OrclWAMP – Migration report", "OrclWAMP – Отчет за миграцията" },
            { "From \"{0}\" (package created {1}) to \"{2}\" – {3}", "От „{0}“ (пакет, създаден на {1}) към „{2}“ – {3}" },
            { "apps installed or already there", "приложения инсталирани или вече налични" },
            { "apps failed", "неуспешни приложения" },
            { "apps to install manually", "приложения за ръчно инсталиране" },
            { "Windows settings applied", "приложени настройки на Windows" },
            { "app settings applied", "приложени настройки на приложения" },
            { "personal files copied", "копирани лични файлове" },
            { "Apps", "Приложения" },
            { "No apps in this package.", "В този пакет няма приложения." },
            { "{0} app(s) were not installed in this session (unticked or not started).", "{0} приложения не са инсталирани в тази сесия (без отметка или не са стартирани)." },
            { "Result", "Резултат" },
            { "Nothing to do.", "Няма нищо за правене." },
            { "Download", "Изтегляне" },
            { "no known link", "няма известна връзка" },
            { "Not copied in this session.", "Не е копирано в тази сесия." },
            { "{0} files copied ({1}), {2} identical files skipped, {3} kept as a renamed copy, {4} failed.", "Копирани файлове: {0} ({1}), пропуснати еднакви файлове: {2}, запазени като преименувано копие: {3}, неуспешни: {4}." },
            { "Not applied in this session.", "Не е приложено в тази сесия." },
            // --- Models.cs
            { "The file is empty or not a valid OrclWAMP package.", "Файлът е празен или не е валиден пакет на OrclWAMP." },
            { "The file contains invalid package IDs: {0}", "Файлът съдържа невалидни ID на пакети: {0}" },
            // --- PackageWriter.cs
            { "{0} sensitive file(s) encrypted with the package password.", "Шифровани с паролата на пакета чувствителни файлове: {0}." },
            { "Manual install list", "Списък за ръчно инсталиране" },
            { "Source PC: {0} · created {1}", "Изходен компютър: {0} · създаден на {1}" },
            { "These apps were installed on the old PC but winget has no package for them, so they have to be installed by hand. Tick them off as you go.", "Тези приложения бяха инсталирани на стария компютър, но winget няма пакет за тях, затова трябва да се инсталират ръчно. Отмятайте ги, докато напредвате." },
            { "Nothing to do – every selected app can be installed by winget.", "Няма нищо за правене – всяко избрано приложение може да се инсталира с winget." },
            { "Version on old PC", "Версия на стария компютър" },
            { "Notes", "Бележки" },
            { "Tip: OrclWAMP.exe (button \"Manual apps & downloads\") can download these one by one or all at once.", "Съвет: OrclWAMP.exe (бутон „Ръчни приложения и изтегляния“) може да ги изтегли едно по едно или всички наведнъж." },
            { "Installed automatically by OrclWAMP ({0})", "Инсталирани автоматично от OrclWAMP ({0})" },
            { "This folder was created on {0} ({1}).", "Тази папка е създадена на {0} ({1})." },
            { "It contains {0} apps that winget can install and {1} apps to install by hand.", "Съдържа {0} приложения, които winget може да инсталира, и {1} приложения за ръчно инсталиране." },
            { "ON THE NEW PC", "НА НОВИЯ КОМПЮТЪР" },
            { "1. Connect it to the internet.", "1. Свържете го с интернет." },
            { "2. Copy this folder to the new PC (or run it straight from the USB stick).", "2. Копирайте тази папка на новия компютър (или я стартирайте направо от USB флашката)." },
            { "3. Double-click Install.cmd (or OrclWAMP.exe).", "3. Щракнете два пъти върху Install.cmd (или OrclWAMP.exe)." },
            { "4. Check the list and click \"Start installation\".", "4. Прегледайте списъка и натиснете „Начало на инсталирането“." },
            { "5. Click \"Manual apps & downloads\" (or open {0}) for the apps that need a manual install.", "5. Натиснете „Ръчни приложения и изтегляния“ (или отворете {0}) за приложенията, които изискват ръчно инсталиране." },
            { "If Windows SmartScreen warns about the exe: click \"More info\" > \"Run anyway\".", "Ако Windows SmartScreen предупреди за exe файла: натиснете „Повече информация“ > „Изпълни въпреки това“." },
            { "FILES", "ФАЙЛОВЕ" },
            { "the installer (the same portable tool that made this folder)", "инсталаторът (същият преносим инструмент, който създаде тази папка)" },
            { "the app list - can be opened and edited in OrclWAMP", "списъкът с приложения - може да се отваря и редактира в OrclWAMP" },
            { "starts OrclWAMP in restore mode", "стартира OrclWAMP в режим на възстановяване" },
            { "standard winget file:", "стандартен winget файл:" },
            { "plain PowerShell fallback:", "резервен вариант с PowerShell:" },
            { "Windows settings from the old PC (button \"Windows settings\" applies them, with Undo)", "настройки на Windows от стария компютър (бутонът „Настройки на Windows“ ги прилага, с възможност за отмяна)" },
            { "apps winget can't install (download links only where certain)", "приложения, които winget не може да инсталира (връзки за изтегляне само където са сигурни)" },
            { "COMMAND LINE", "КОМАНДЕН РЕД" },
            { "open restore mode", "отваряне на режима на възстановяване" },
            { "install everything without asking (use with /restore)", "инсталиране на всичко без питане (използва се с /restore)" },
            { "Logs from each run are saved in this folder (OrclWAMP-restore-*.log).", "Дневниците от всяко изпълнение се записват в тази папка (OrclWAMP-restore-*.log)." },
            // --- PasswordDialog.cs
            { "Password", "Парола" },
            { "Show password", "Покажи паролата" },
            { "Type it again:", "Въведете я отново:" },
            { "Use at least {0} characters.", "Използвайте поне {0} знака." },
            { "The two passwords are different.", "Двете пароли са различни." },
            { "Please enter the password.", "Въведете паролата." },
            // --- PersonalFiles.cs
            { "   skipped (too big for this drive's FAT32 format): {0}", "   пропуснат (твърде голям за FAT32 формата на това устройство): {0}" },
            { "   could not copy {0}: {1}", "   {0} не можа да бъде копиран: {1}" },
            { "Copying {0}…", "Копиране на {0}…" },
            { "   {0} files copied, {1} failed.", "   Копирани файлове: {0}, неуспешни: {1}." },
            // --- Program.cs
            { "/csv needs a file name.", "/csv изисква име на файл." },
            { "/package needs a folder.", "/package изисква папка." },
            { "Unknown option: {0}", "Непознат параметър: {0}" },
            { "Scan this PC (or restore, if a package file is next to the exe)", "Сканиране на този компютър (или възстановяване, ако до exe файла има пакет)" },
            { "Always open the scanner", "Винаги отваря скенера" },
            { "Install apps from a migration package", "Инсталиране на приложения от пакет за миграция" },
            { "Install everything without asking", "Инсталиране на всичко без питане" },
            { "Scan and write a migration package without UI", "Сканиране и записване на пакет за миграция без интерфейс" },
            { "Scan and save the app list as CSV without UI", "Сканиране и запис на списъка с приложения като CSV без интерфейс" },
            { "Show app updates for this PC", "Показване на актуализациите на приложения за този компютър" },
            { "Open migration package", "Отваряне на пакет за миграция" },
            { "OrclWAMP package (*.json)|*.json|All files|*.*", "Пакет на OrclWAMP (*.json)|*.json|Всички файлове|*.*" },
            { "Could not read the package file:", "Файлът на пакета не можа да бъде прочетен:" },
            { "Unexpected error:", "Неочаквана грешка:" },
            // --- RestoreForm.cs
            { "Checking winget…", "Проверка на winget…" },
            { "Install apps on this PC", "Инсталиране на приложения на този компютър" },
            { "Tick all", "Отметни всички" },
            { "Untick all", "Премахни всички отметки" },
            { "Tick only failed", "Отметни само неуспешните" },
            { "Skip apps that are already installed", "Пропускане на вече инсталираните приложения" },
            { "Restart the PC when finished", "Рестартиране на компютъра след приключване" },
            { "Start installation", "Начало на инсталирането" },
            { "Stopping… (the current installer is being terminated)", "Спиране… (текущият инсталатор се прекратява)" },
            { "Skipping the check…", "Пропускане на проверката…" },
            { "Retry failed", "Повтори неуспешните" },
            { "Manual apps && downloads ({0})", "Ръчни приложения и изтегляния ({0})" },
            { "Open log", "Отвори дневника" },
            { "No log has been written yet.", "Все още няма записан дневник." },
            { "Windows settings ({0})", "Настройки на Windows ({0})" },
            { "App settings & bookmarks ({0})", "Настройки на приложения и отметки ({0})" },
            { "Personal files ({0})", "Лични файлове ({0})" },
            { "Migration report", "Отчет за миграцията" },
            { "{0} apps from \"{1}\"  ·  package created {2}", "{0} приложения от „{1}“  ·  пакетът е създаден на {2}" },
            { "Install / repair winget", "Инсталиране / поправка на winget" },
            { "Restart as administrator", "Рестартиране като администратор" },
            { "Waiting", "Изчакване" },
            { "{0} {1} – restore on {2} as {3}", "{0} {1} – възстановяване на {2} като {3}" },
            { "(administrator)", "(администратор)" },
            { "Package: {0}", "Пакет: {0}" },
            { "Warning: running as a different account ({0}) than the one that started OrclWAMP.", "Внимание: изпълнява се с друг акаунт ({0}), а не с този, който стартира OrclWAMP." },
            { "Administrator rights were granted with a different account ({0}).", "Администраторските права са дадени с друг акаунт ({0})." },
            { "Apps that install per user (and Store apps) would end up in THAT account, not yours.", "Приложенията, които се инсталират за отделен потребител (и приложенията от Store), ще попаднат в ТОЗИ акаунт, а не във вашия." },
            { "Continue as {0} anyway?", "Продължаване като {0} въпреки това?" },
            { "No = continue without administrator rights (recommended)", "Не = продължаване без администраторски права (препоръчително)" },
            { "Continuing without administrator rights – some installers will show their own UAC prompt.", "Продължаване без администраторски права – някои инсталатори ще покажат свое UAC запитване." },
            { "OrclWAMP or the package is on a network drive, which administrator processes can't see – not elevating.", "OrclWAMP или пакетът е на мрежово устройство, което администраторските процеси не виждат – без повишаване на правата." },
            { "The package is on a network drive, which isn't visible to administrator processes.\r\nCopy the folder to this PC or a USB stick first.", "Пакетът е на мрежово устройство, което не се вижда от администраторските процеси.\r\nПърво копирайте папката на този компютър или на USB флашка." },
            { "Administrator rights were not granted.", "Не бяха дадени администраторски права." },
            { "Started an administrator copy of OrclWAMP – waiting for it to finish…", "Стартирано е копие на OrclWAMP с администраторски права – изчакване да приключи…" },
            { "Continuing without administrator rights.", "Продължаване без администраторски права." },
            { "The administrator copy ended unexpectedly (exit code {0}) – continuing here without administrator rights.", "Администраторското копие приключи неочаквано (код {0}) – продължаване тук без администраторски права." },
            { "Update winget", "Актуализиране на winget" },
            { "winget {0} is outdated – updating is recommended.", "winget {0} е остарял – препоръчва се актуализиране." },
            { "winget {0} is ready.", "winget {0} е готов." },
            { "winget was not found on this PC – click \"Install / repair winget\".", "winget не е открит на този компютър – натиснете „Инсталиране / поправка на winget“." },
            { "Checking which apps are already installed… (click Stop to skip)", "Проверка кои приложения вече са инсталирани… (натиснете „Спри“, за да пропуснете)" },
            { "Warning: winget returned no installed packages – the already-installed check was skipped.", "Внимание: winget не върна инсталирани пакети – проверката за вече инсталирани беше пропусната." },
            { "Already installed", "Вече е инсталирано" },
            { "{0} of {1} apps are already installed on this PC.", "{0} от {1} приложения вече са инсталирани на този компютър." },
            { "{0} apps to install. Review the list, then click \"Start installation\".", "{0} приложения за инсталиране. Прегледайте списъка и натиснете „Начало на инсталирането“." },
            { "Already-installed check skipped.", "Проверката за вече инсталирани е пропусната." },
            { "Review the list, then click \"Start installation\".", "Прегледайте списъка и натиснете „Начало на инсталирането“." },
            { "Could not check installed apps: {0}", "Инсталираните приложения не можаха да бъдат проверени: {0}" },
            { "Registering App Installer (attempt {0} of 3)…", "Регистриране на App Installer (опит {0} от 3)…" },
            { "Registering the built-in App Installer package…", "Регистриране на вградения пакет App Installer…" },
            { "Downloading winget from Microsoft (GitHub) – this can take a few minutes…", "Изтегляне на winget от Microsoft (GitHub) – това може да отнеме няколко минути…" },
            { "Downloading App Installer and its dependencies from github.com/microsoft/winget-cli …", "Изтегляне на App Installer и зависимостите му от github.com/microsoft/winget-cli …" },
            { "App Installer setup finished.", "Инсталирането на App Installer приключи." },
            { "App Installer setup failed (exit code {0}).", "Инсталирането на App Installer е неуспешно (код {0})." },
            { "winget setup failed: {0}", "Инсталирането на winget е неуспешно: {0}" },
            { "winget could not be installed automatically.", "winget не можа да бъде инсталиран автоматично." },
            { "Install \"App Installer\" from the Microsoft Store (or run Windows Update), then click \"Install / repair winget\" again.\r\n\r\nOpen the Microsoft Store page now?", "Инсталирайте „App Installer“ от Microsoft Store (или пуснете Windows Update), след това натиснете отново „Инсталиране / поправка на winget“.\r\n\r\nДа се отвори ли страницата в Microsoft Store сега?" },
            { "Installing {0} app(s) – {1}", "Инсталиране на {0} приложения – {1}" },
            { "Queued", "На опашката" },
            { "Skipped (stopped)", "Пропуснато (спряно)" },
            { "Installing {0} of {1}: {2}", "Инсталиране {0} от {1}: {2}" },
            { "Installing…", "Инсталиране…" },
            { "Finished in {0}: {1} installed, {2} already present, {3} failed/skipped.", "Приключи за {0}: инсталирани {1}, вече налични {2}, неуспешни/пропуснати {3}." },
            { "not installed: {0} ({1})", "не е инсталирано: {0} ({1})" },
            { "Restarting the PC in 60 seconds (run \"shutdown /a\" to abort).", "Компютърът ще се рестартира след 60 секунди (изпълнете „shutdown /a“, за да откажете)." },
            { "Could not schedule restart: {0}", "Рестартирането не можа да бъде насрочено: {0}" },
            { "Click \"Retry failed\" to try the failed apps again.", "Натиснете „Повтори неуспешните“, за да опитате отново неуспешните приложения." },
            { "Some apps refuse to install as administrator. Close OrclWAMP, start it again, answer \"No\" to the administrator prompt and click \"Retry failed\".", "Някои приложения отказват да се инсталират като администратор. Затворете OrclWAMP, стартирайте го отново, отговорете с „Не“ на запитването за администраторски права и натиснете „Повтори неуспешните“." },
            { "Some apps need a restart to finish installing.", "Някои приложения изискват рестартиране, за да завърши инсталирането." },
            { "Don't forget the {0} apps on the manual-install list (button \"Manual apps & downloads\").", "Не забравяйте {0} приложения в списъка за ръчно инсталиране (бутон „Ръчни приложения и изтегляния“)." },
            { "The PC restarts in 60 seconds.", "Компютърът ще се рестартира след 60 секунди." },
            { "Unexpected error: {0}", "Неочаквана грешка: {0}" },
            { "Stopped because of an error – see the log.", "Спряно поради грешка – вижте дневника." },
            { "Version {0} could not be installed ({1}) – trying the latest version instead.", "Версия {0} не можа да бъде инсталирана ({1}) – опит с най-новата версия." },
            { "{0} – waiting 60 seconds and trying again ({1} of 3)…", "{0} – изчакване 60 секунди и нов опит ({1} от 3)…" },
            { "Waiting to retry…", "Изчакване за нов опит…" },
            { "Downloading {0}", "Изтегляне {0}" },
            { "No internet connection detected.", "Не е открита интернет връзка." },
            { "This PC doesn't seem to be connected to the internet. winget needs internet access to download the apps.\r\n\r\nTry anyway?", "Изглежда този компютър не е свързан с интернет. winget се нуждае от интернет, за да изтегли приложенията.\r\n\r\nОпит въпреки това?" },
            { "Waiting for an internet connection…", "Изчакване на интернет връзка…" },
            { "Internet connection is up.", "Интернет връзката е налична." },
            { "Still no internet connection after 10 minutes – installation not started.", "Все още няма интернет връзка след 10 минути – инсталирането не е започнато." },
            { "No internet connection – installation not started.", "Няма интернет връзка – инсталирането не е започнато." },
            { "Every app in this package can be installed by winget – nothing to install manually.", "Всяко приложение в този пакет може да се инсталира с winget – няма нищо за ръчно инсталиране." },
            { "Could not save the link in the package: {0}", "Връзката не можа да бъде записана в пакета: {0}" },
            { "Please wait until the installation has finished.", "Изчакайте инсталирането да приключи." },
            { "Not installed in this session", "Не е инсталирано в тази сесия" },
            { "The report could not be saved.", "Отчетът не можа да бъде записан." },
            { "Applying app settings & bookmarks…", "Прилагане на настройки на приложения и отметки…" },
            { "App settings: {0} applied, {1} skipped.", "Настройки на приложения: приложени {0}, пропуснати {1}." },
            { "Copying personal files…", "Копиране на лични файлове…" },
            { "Personal files: {0} copied, {1} skipped, {2} failed.", "Лични файлове: копирани {0}, пропуснати {1}, неуспешни {2}." },
            { "Migration report:", "Отчет за миграцията:" },
            { "Applying Windows settings from {0}…", "Прилагане на настройки на Windows от {0}…" },
            { "Wi-Fi networks skipped – they are password-protected (use the \"Windows settings\" button).", "Wi-Fi мрежите са пропуснати – защитени са с парола (използвайте бутона „Настройки на Windows“)." },
            { "Windows settings: {0} applied, {1} skipped. Backup: {2}", "Настройки на Windows: приложени {0}, пропуснати {1}. Резервно копие: {2}" },
            { "File Explorer restarted.", "File Explorer е рестартиран." },
            { "Windows settings could not be applied: {0}", "Настройките на Windows не можаха да бъдат приложени: {0}" },
            { "Apps are still being installed. Stop and close?", "Приложенията все още се инсталират. Спиране и затваряне?" },
            { "Stopping the current installer…", "Спиране на текущия инсталатор…" },
            // --- Scanner.cs
            { "Reading installed apps (winget list)…", "Четене на инсталираните приложения (winget list)…" },
            { "winget did not return a list of installed apps.", "winget не върна списък с инсталирани приложения." },
            { "Verifying package IDs (winget export)…", "Проверка на ID на пакетите (winget export)…" },
            { "Classifying apps…", "Класифициране на приложенията…" },
            // --- SearchForm.cs
            { "Type a name (e.g. \"firefox\") and press Enter.", "Въведете име (напр. „firefox“) и натиснете Enter." },
            { "Add apps from winget", "Добавяне на приложения от winget" },
            { "Add ticked apps", "Добави отметнатите приложения" },
            { "Search winget:", "Търсене в winget:" },
            { "Search", "Търси" },
            { "Type at least 2 characters.", "Въведете поне 2 знака." },
            { "Searching…", "Търсене…" },
            { "No packages found.", "Не са открити пакети." },
            { "{0} result(s). Tick the apps to add (double-click toggles).", "Резултати: {0}. Отметнете приложенията за добавяне (двойното щракване превключва отметката)." },
            { "{0} result(s) hidden – search more specifically.", "Скрити резултати: {0} – търсете по-конкретно." },
            { "Tick at least one app first.", "Първо отметнете поне едно приложение." },
            // --- Secrets.cs
            { "Wrong password (or the protected file is damaged).", "Грешна парола (или защитеният файл е повреден)." },
            { "This package has password-protected items (Wi-Fi passwords, SSH keys). Enter the package password:", "Този пакет съдържа елементи, защитени с парола (пароли за Wi-Fi, SSH ключове). Въведете паролата на пакета:" },
            // --- Settings.cs
            { "A backup of the current settings could not be saved, so nothing was changed.", "Не можа да бъде записано резервно копие на текущите настройки, затова нищо не е променено." },
            { "skipped (not an allowed setting): {0}", "пропуснато (непозволена настройка): {0}" },
            { "skipped {0}: {1}", "пропуснато {0}: {1}" },
            { "protected by Windows", "защитено от Windows" },
            { "Could not update the backup: {0}", "Резервното копие не можа да бъде обновено: {0}" },
            { "unknown value type", "непознат тип стойност" },
            { "value too large", "твърде голяма стойност" },
            { "unsupported value type", "неподдържан тип стойност" },
            { "value too long", "твърде дълга стойност" },
            { "input languages and keyboard layouts set: {0}", "зададени езици за въвеждане и клавиатурни подредби: {0}" },
            { "could not set the input languages: {0}", "езиците за въвеждане не можаха да бъдат зададени: {0}" },
            { "wallpaper set", "тапетът е зададен" },
            { "could not set {0}", "{0} не можа да бъде зададено" },
            { "{0} power setting(s) applied", "приложени настройки на захранването: {0}" },
            { "font {0}: {1}", "шрифт {0}: {1}" },
            { "{0} font(s) installed", "инсталирани шрифтове: {0}" },
            { "could not add Wi-Fi profile {0}", "Wi-Fi профилът {0} не можа да бъде добавен" },
            { "{0} Wi-Fi network(s) added", "добавени Wi-Fi мрежи: {0}" },
            // --- SettingsForm.cs
            { "Windows settings to take along", "Настройки на Windows за пренасяне" },
            { "Setting", "Настройка" },
            { "Found on this PC", "Открито на този компютър" },
            { "checking…", "проверка…" },
            { "Use these settings", "Използвай тези настройки" },
            { "All (except Wi-Fi)", "Всички (без Wi-Fi)" },
            { "These personal Windows settings are copied into the migration package and can be applied on the new PC (OrclWAMP makes a backup there first, so they can be undone). Only per-user settings from this list are ever written.", "Тези лични настройки на Windows се копират в пакета за миграция и могат да бъдат приложени на новия компютър (OrclWAMP първо прави резервно копие там, така че могат да бъдат отменени). Записват се само потребителски настройки от този списък." },
            { "Apply Windows settings", "Прилагане на настройки на Windows" },
            { "Restarts File Explorer", "Рестартира File Explorer" },
            { "Apply ticked settings", "Приложи отметнатите настройки" },
            { "Settings from \"{0}\" – {1}, saved {2}.  This PC: {3}.", "Настройки от „{0}“ – {1}, записани на {2}.  Този компютър: {3}." },
            { "The settings come from {0} – a few taskbar/Start options may not exist on this Windows version (they are simply ignored).", "Настройките са от {0} – някои опции на лентата на задачите/менюто „Старт“ може да липсват в тази версия на Windows (те просто се пренебрегват)." },
            { "A backup of your current settings is made before anything is changed – \"Undo last apply\" puts them back.", "Преди всяка промяна се прави резервно копие на текущите настройки – „Отмяна на последното прилагане“ ги връща обратно." },
            { "Reading settings on this PC…", "Четене на настройките на този компютър…" },
            { "nothing found", "нищо не е открито" },
            { "{0} values + languages", "{0} стойности + езици" },
            { "power plan values", "стойности на плана за захранване" },
            { "picture + fit", "картина + разположение" },
            { "{0} values", "{0} стойности" },
            { "{0} font(s)", "шрифтове: {0}" },
            { "saved networks", "запазени мрежи" },
            { "No settings are ticked.", "Няма отметнати настройки." },
            { "Wi-Fi networks skipped – the package password was not entered.", "Wi-Fi мрежите са пропуснати – паролата на пакета не е въведена." },
            { "Applying settings…", "Прилагане на настройките…" },
            { "Applying {0} setting group(s) – {1}", "Прилагане на {0} групи настройки – {1}" },
            { "Failed: {0}", "Неуспех: {0}" },
            { "Backup: {0}", "Резервно копие: {0}" },
            { "{0} settings applied, {1} skipped.", "Приложени настройки: {0}, пропуснати: {1}." },
            { "Put back the settings as they were before the last \"Apply\"?\r\n\r\n(Fonts and Wi-Fi networks that were added stay installed.)", "Да се върнат ли настройките както бяха преди последното „Прилагане“?\r\n\r\n(Добавените шрифтове и Wi-Fi мрежи остават инсталирани.)" },
            { "Restoring previous settings…", "Възстановяване на предишните настройки…" },
            { "Undo failed: {0}", "Неуспешна отмяна: {0}" },
            { "Undo: {0} values restored.", "Отмяна: възстановени стойности: {0}." },
            { "Previous settings restored.", "Предишните настройки са възстановени." },
            { "Restart File Explorer now so the taskbar, Start and colour settings show up?\r\n\r\n(Open Explorer windows will close.)", "Да се рестартира ли File Explorer сега, за да се покажат настройките на лентата на задачите, „Старт“ и цветовете?\r\n\r\n(Отворените прозорци на Explorer ще се затворят.)" },
            { "Restarting File Explorer…", "Рестартиране на File Explorer…" },
            { "Some settings (touchpad, keyboard, languages) take full effect after you sign out and back in – or restart the PC when you're done.", "Някои настройки (тъчпад, клавиатура, езици) влизат напълно в сила, след като излезете и влезете отново – или рестартирайте компютъра, когато приключите." },
            // --- Ui.cs
            { "Log: move to bottom ⤓", "Дневник: премести долу ⤓" },
            { "Log: move to right ⇥", "Дневник: премести вдясно ⇥" },
            { "Show the log below the list or next to it", "Показване на дневника под списъка или до него" },
            { "New version {0} available", "Налична е нова версия {0}" },
            { "Light", "Светла" },
            { "Light theme", "Светла тема" },
            { "Dark", "Тъмна" },
            { "Dark theme", "Тъмна тема" },
            { "System", "Системна" },
            { "Follow the Windows setting", "Според настройката на Windows" },
            // --- UpgradeForm.cs
            { "App updates", "Актуализации на приложения" },
            { "Installed", "Инсталирано" },
            { "Available", "Налично" },
            { "Update ticked apps", "Актуализирай отметнатите приложения" },
            { "Check again", "Провери отново" },
            { "Apps on this PC that have a newer version in winget. Tick the ones to update – installers run silently, one after another.", "Приложения на този компютър, които имат по-нова версия в winget. Отметнете тези за актуализиране – инсталаторите се изпълняват безшумно, един след друг." },
            { "Updates are still running. Stop and close?", "Актуализациите все още се изпълняват. Спиране и затваряне?" },
            { "winget was not found on this PC.", "winget не е открит на този компютър." },
            { "Looking for updates…", "Търсене на актуализации…" },
            { "Everything is up to date.", "Всичко е актуално." },
            { "{0} update(s) available.", "Налични актуализации: {0}." },
            { "Updating…", "Актуализиране…" },
            { "Updating {0} of {1}: {2}", "Актуализиране {0} от {1}: {2}" },
            { "Up to date", "Актуално" },
            { "{0} updated, {1} failed or skipped.", "Актуализирани: {0}, неуспешни или пропуснати: {1}." },
            // --- Winget.cs
            { "Cancelled", "Отменено" },
            { "Timed out", "Времето за изчакване изтече" },
            { "Could not start winget: {0}", "winget не можа да бъде стартиран: {0}" },
            { "A newer version is already installed", "Вече е инсталирана по-нова версия" },
            { "Installed – restart required", "Инсталирано – нужно е рестартиране" },
            { "Installed – restart started by installer", "Инсталирано – инсталаторът стартира рестартиране" },
            { "Failed – restart the PC, then click \"Retry failed\"", "Неуспех – рестартирайте компютъра, след това натиснете „Повтори неуспешните“" },
            { "Package not found in source", "Пакетът не е открит в източника" },
            { "More than one package matched", "Съвпада повече от един пакет" },
            { "No installer for this system (architecture / OS)", "Няма инсталатор за тази система (архитектура / ОС)" },
            { "Failed – download failed", "Неуспех – изтеглянето е неуспешно" },
            { "Failed – installer hash mismatch (package being updated, try later)", "Неуспех – несъвпадащ хеш на инсталатора (пакетът се обновява, опитайте по-късно)" },
            { "Microsoft Store is blocked by policy", "Microsoft Store е блокиран от груповите правила" },
            { "Failed – Microsoft Store install failed", "Неуспех – инсталирането от Microsoft Store е неуспешно" },
            { "Failed – could not open the package source", "Неуспех – източникът на пакети не можа да бъде отворен" },
            { "Failed – source agreements not accepted", "Неуспех – споразуменията на източника не са приети" },
            { "Can't install as administrator – run OrclWAMP without admin rights and retry", "Не може да се инсталира като администратор – стартирайте OrclWAMP без администраторски права и опитайте отново" },
            { "Per-user app – run OrclWAMP without admin rights and retry", "Приложение за отделен потребител – стартирайте OrclWAMP без администраторски права и опитайте отново" },
            { "Failed – a dependency could not be installed", "Неуспех – зависимост не можа да бъде инсталирана" },
            { "Failed – app is in use by another application", "Неуспех – приложението се използва от друго приложение" },
            { "Failed – another installation is in progress", "Неуспех – тече друго инсталиране" },
            { "Failed – application is in use", "Неуспех – приложението се използва" },
            { "Failed – a file is in use", "Неуспех – файл се използва" },
            { "Failed – missing dependency", "Неуспех – липсва зависимост" },
            { "Failed – disk full", "Неуспех – дискът е пълен" },
            { "Failed – not enough memory", "Неуспех – няма достатъчно памет" },
            { "Failed – no network connection", "Неуспех – няма мрежова връзка" },
            { "Cancelled by user (installer)", "Отменено от потребителя (инсталатор)" },
            { "Blocked by policy", "Блокирано от правила" },
            { "Failed (exit code 0x{0})", "Неуспех (код 0x{0})" },
            // --- Settings.cs(cat)
            { "Touchpad & gestures", "Тъчпад и жестове" },
            { "Taps, two-finger scroll direction, three- and four-finger swipes and taps, sensitivity, cursor speed", "Докосвания, посока на превъртане с два пръста, плъзгания и докосвания с три и четири пръста, чувствителност, скорост на курсора" },
            { "Takes full effect after signing out", "Влиза напълно в сила след излизане от акаунта" },
            { "Mouse & pointer", "Мишка и показалец" },
            { "Pointer speed and acceleration, double-click speed, primary button, wheel scroll lines, pointer scheme, size and colour", "Скорост и ускорение на показалеца, скорост на двойното щракване, основен бутон, редове за превъртане с колелцето, схема, размер и цвят на показалеца" },
            { "Keyboard & languages", "Клавиатура и езици" },
            { "Input languages and keyboard layouts, layout-switch hotkey, key repeat delay and rate, NumLock at start-up, Sticky/Toggle/Filter Keys shortcuts", "Езици за въвеждане и клавиатурни подредби, клавишна комбинация за смяна на подредбата, забавяне и скорост на повторение на клавишите, NumLock при стартиране, бързи клавиши за Залепващи/Превключващи/Филтриращи клавиши" },
            { "Some parts take effect after signing out", "Някои части влизат в сила след излизане от акаунта" },
            { "Taskbar, Start & File Explorer", "Лента на задачите, „Старт“ и File Explorer" },
            { "File extensions, hidden files, open-to folder, taskbar alignment/buttons/combining/auto-hide, search box, Start recommendations, Snap and Alt+Tab, clock seconds", "Разширения на файловете, скрити файлове, начална папка, подравняване/бутони/групиране/автоматично скриване на лентата на задачите, поле за търсене, препоръки в „Старт“, Snap и Alt+Tab, секунди на часовника" },
            { "Colours & theme", "Цветове и тема" },
            { "Light or dark mode for apps and Windows, accent colour, accent on Start/taskbar and title bars, transparency", "Светъл или тъмен режим за приложенията и Windows, акцентен цвят, акцент в „Старт“/лентата на задачите и заглавните ленти, прозрачност" },
            { "Wallpaper", "Тапет" },
            { "The desktop picture (copied into the package) and how it is fitted", "Картината на работния плот (копира се в пакета) и как е разположена" },
            { "Desktop & multitasking", "Работен плот и многозадачност" },
            { "Clipboard history, menu delay, cursor blink rate, show window contents while dragging, font smoothing, visual effects choice", "История на клипборда, забавяне на менютата, скорост на мигане на курсора, показване на съдържанието на прозореца при влачене, изглаждане на шрифтовете, избор на визуални ефекти" },
            { "Regional formats", "Регионални формати" },
            { "Date, time, number and currency formats, first day of week, measurement system, region", "Формати за дата, час, числа и валута, първи ден от седмицата, мерна система, регион" },
            { "Power: screen & sleep", "Захранване: екран и заспиване" },
            { "Turn off screen / sleep / hibernate after (on battery and plugged in), lid close and power button actions", "Изключване на екрана / заспиване / хибернация след (на батерия и включен в мрежата), действия при затваряне на капака и бутона за захранване" },
            { "Applied to the active power plan", "Прилага се към активния план за захранване" },
            { "User-installed fonts", "Шрифтове, инсталирани от потребителя" },
            { "Fonts you installed yourself (\"Install for me\") – copied into the package", "Шрифтове, които сте инсталирали сами („Инсталиране за мен“) – копират се в пакета" },
            { "Wi-Fi networks (with passwords)", "Wi-Fi мрежи (с пароли)" },
            { "Saved Wi-Fi networks so the new PC connects automatically – only in a password-protected package (encrypted)", "Запазени Wi-Fi мрежи, за да се свързва новият компютър автоматично – само в пакет, защитен с парола (шифровани)" },
            { "{0}: not replaced – {1} file(s) could not be backed up first", "{0}: не е заменено – резервно копие не можа да се направи за файлове: {1}" },
            { "OrclWAMP finished installing apps. Restarting in 60 seconds.", "OrclWAMP приключи инсталирането на приложенията. Рестартиране след 60 секунди." },
            { "OrclWAMP is still working. Stop and close?", "OrclWAMP все още работи. Да се спре и затвори ли?" },
            { "Stopping…", "Спиране…" },
            { "skipped the \"{0}\" folder – it contains scripts that would run on this PC. Copy it by hand if you need it.", "пропусната е папката „{0}“ – съдържа скриптове, които биха се изпълнявали на този компютър. Копирайте я ръчно, ако ви трябва." },
            { "\"{0}\" is inside the package folder. Choose another folder to copy, or save the package somewhere else.", "„{0}“ е вътре в папката на пакета. Изберете друга папка за копиране или запишете пакета другаде." },
            { "{0}: not replaced – it contains links or folders that can't be backed up", "{0}: не е заменено – съдържа връзки или папки, от които не може да се направи резервно копие" },
            { "Your previous files were backed up to {0} (needed for Undo) – delete that folder when you no longer need it.", "Предишните ви файлове са копирани в {0} (нужно за отмяна) – изтрийте тази папка, когато вече не ви трябва." },
            { "{0}: skipped in unattended mode – apply it with the \"App settings & bookmarks\" button.", "{0}: пропуснато в автоматичния режим – приложете го с бутона „Настройки на приложения и отметки“." },
            { "Some files could not be restored – the folder as it was before Undo is kept in {0}", "Някои файлове не можаха да бъдат възстановени – папката във вида ѝ преди отмяната е запазена в {0}" },
            { "The package folder is inside \"{0}\", which is being copied. Save the package somewhere else (e.g. a USB drive).", "Папката на пакета е вътре в „{0}“, която се копира. Запишете пакета другаде (например на USB флашка)." },
            { "These items can run commands on this PC:\r\n\r\n{0}\r\n\r\nOnly apply them if the package was made by you. Continue?", "Тези елементи могат да изпълняват команди на този компютър:\r\n\r\n{0}\r\n\r\nПрилагайте ги само ако пакетът е създаден от вас. Продължаване?" },
            { "Tip: use a long passphrase of several words – anyone who finds the USB stick could try to guess it.", "Съвет: използвайте дълга фраза от няколко думи – всеки, който намери USB флашката, може да опита да я познае." },
            { "Wi-Fi networks (with their passwords) are only taken along in a password-protected package. Tick \"Protect with password\" in the main window first.", "Wi-Fi мрежите (с паролите им) се пренасят само в пакет, защитен с парола. Първо отметнете „Защита с парола“ в главния прозорец." },
            { "Wi-Fi passwords and SSH keys were left out – they are only included in a password-protected package.", "Паролите за Wi-Fi и SSH ключовете бяха пропуснати – те се включват само в пакет, защитен с парола." },
            // --- AppConfigs.cs(cat)
            { "Microsoft Edge bookmarks", "Отметки на Microsoft Edge" },
            { "Favourites bar and all bookmarks (default profile)", "Лента с любими и всички отметки (профил по подразбиране)" },
            { "If you sign in to Edge with sync on, synced favourites are merged later", "Ако влезете в Edge с включена синхронизация, синхронизираните любими се обединяват по-късно" },
            { "Google Chrome bookmarks", "Отметки на Google Chrome" },
            { "Bookmarks bar and all bookmarks (default profile)", "Лента с отметки и всички отметки (профил по подразбиране)" },
            { "Brave bookmarks", "Отметки на Brave" },
            { "Firefox bookmarks", "Отметки на Firefox" },
            { "Latest bookmark backup – placed on the Desktop to restore in Firefox", "Последният архив на отметките – поставя се на работния плот за възстановяване във Firefox" },
            { "Firefox: Bookmarks > Manage bookmarks > Import and Backup > Restore > Choose File", "Firefox: Отметки > Управление на отметките > Внасяне и архивиране > Възстановяване > Избор на файл" },
            { "Windows Terminal", "Windows Terminal" },
            { "Profiles, colour schemes, key bindings (settings.json)", "Профили, цветови схеми, клавишни комбинации (settings.json)" },
            { "Visual Studio Code", "Visual Studio Code" },
            { "Settings, key bindings, snippets and the list of extensions (reinstalled)", "Настройки, клавишни комбинации, фрагменти и списъкът с разширения (инсталират се отново)" },
            { "Notepad++", "Notepad++" },
            { "Preferences, shortcuts, styles, context menu, user languages and themes", "Предпочитания, бързи клавиши, стилове, контекстно меню, потребителски езици и теми" },
            { "Double Commander", "Double Commander" },
            { "All settings, hotkeys, favourite folders", "Всички настройки, клавишни комбинации, любими папки" },
            { "Total Commander", "Total Commander" },
            { "Main settings (wincmd.ini)", "Основни настройки (wincmd.ini)" },
            { "PowerShell profiles", "Профили на PowerShell" },
            { "Your PowerShell start-up scripts (Windows PowerShell and PowerShell 7)", "Вашите стартови скриптове на PowerShell (Windows PowerShell и PowerShell 7)" },
            { "Git", "Git" },
            { "Your name, e-mail and Git options (.gitconfig)", "Вашето име, имейл и настройки на Git (.gitconfig)" },
            { "SSH keys", "SSH ключове" },
            { "Your SSH keys and config (.ssh) – only in a password-protected package", "Вашите SSH ключове и конфигурация (.ssh) – само в пакет, защитен с парола" },
            // --- Downloads.cs(cat)
            { "Install Battle.net, then install the game from it", "Инсталирайте Battle.net, след това инсталирайте играта от него" },
            { "The NVIDIA app installs the latest driver", "Приложението NVIDIA инсталира най-новия драйвер" },
            { "Driver – AMD auto-detect tool", "Драйвер – инструмент на AMD за автоматично откриване" },
            { "Sign in and choose \"Install apps\"", "Влезте и изберете „Инсталиране на приложения“" },
            // --- Scanner.cs(cat)
            { "Package ID could not be read – install manually", "ID на пакета не можа да бъде прочетено – инсталирайте ръчно" },
            { "Runtime – installed automatically when needed", "Среда за изпълнение – инсталира се автоматично при нужда" },
            { "Included with Windows", "Включено в Windows" },
            { "Windows / driver component", "Компонент на Windows / драйвер" },
            { "Web app – reinstall it from the browser", "Уеб приложение – инсталирайте го отново от браузъра" },
            { "Driver – get it from the hardware maker", "Драйвер – вземете го от производителя на хардуера" },
            { "Not in winget – goes to the manual-install list", "Няма го в winget – отива в списъка за ръчно инсталиране" },
            // --- MainForm.cs(cat)
            { "Added from winget search", "Добавено от търсене в winget" },
            { "Found by name in winget", "Открито по име в winget" },
            // --- PersonalFiles.cs(cat)
            { "Desktop", "Работен плот" },
            { "Documents", "Документи" },
            { "Pictures", "Снимки" },
            { "Music", "Музика" },
            { "Videos", "Видеоклипове" },
            { "Downloads", "Изтегляния" },
        };
    }
}
